# 5x5 Via array example

**Author:** Allan Sánchez Masís

**Last update by:** Allan Sánchez Masís

**Link of database:**https://www.tet.tuhh.de/en/si-pi-database/

**Link of papers:**
<ul>
    <li>https://ieeexplore.ieee.org/document/9361755</li>
    <li>https://ieeexplore.ieee.org/document/9505202</li>
    <li>https://ieeexplore.ieee.org/document/10375594</li>
</ul>



## Imports

In [49]:
import keras
from keras.models import Sequential
from keras.layers         import Dense, Dropout, Flatten
from keras.utils.np_utils import to_categorical
from keras.callbacks      import EarlyStopping, Callback
from keras.layers         import Conv2D, MaxPooling2D, Conv1D
from keras                import backend as K
import pandas
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, MinMaxScaler
from sklearn.externals.joblib import dump, load
from keras.models import load_model

import matplotlib.pyplot as plt

from sklearn.model_selection import train_test_split




import logging



## Data split and import data
Data split

In [62]:
def get_values_and_header(csv_matrix):
    csv_matrix=csv_matrix.values
    matrix_values=csv_matrix[1:,0:]
    matrix_values=np.asfarray(matrix_values,float)
    vector_header=csv_matrix[0,0:]
    return matrix_values, vector_header


def separador_de_features(features_amount,dataset,features):
    contafeatures=0
    features=np.reshape(features, (1, features_amount))
    print(features)

    for i in range(0,len(dataset)):
        for j in range(0,features_amount):
            if features[contafeatures][j]!=dataset[i][j]:
                son_iguales=False
                break
            else:
                son_iguales=True
        if son_iguales==False:
            dataset_sub_i_2d=np.reshape(dataset[i,0:features_amount], (1, features_amount))
            features=np.concatenate((features,dataset_sub_i_2d))
            contafeatures=contafeatures+1
    return features


def train_test_full(features_amount,dataset,x_test,outputs_amount):
        conta_iguales=0
        data_test_full=np.ones((1,features_amount+1+outputs_amount))
        print(data_test_full)

        for i in range(0,len(x_test)):
            #rows_dataset=len(dataset)
            for j in range(0,len(dataset)):
                    for k in range(0,features_amount):
                        if x_test[i][k]!=dataset[j-conta_iguales][k]:
                            son_iguales=False
                            break
                        else:
                            son_iguales=True
                    if son_iguales==True:
                        dataset_sub_i_2d=np.reshape(dataset[j-conta_iguales,0:features_amount+1+outputs_amount], (1, features_amount+1+outputs_amount))
                        data_test_full=np.concatenate((data_test_full,dataset_sub_i_2d))
                        dataset=np.delete(dataset, j-conta_iguales, axis=0)
                        conta_iguales=conta_iguales+1
            print(str((i+1)/len(x_test)*100)+"%")
            conta_iguales=0
        data_test_full=data_test_full[1:len(data_test_full),:]
        return data_test_full, dataset


dataset = pandas.read_csv("C:/path/little_sample_to_prove.csv", header=None)
dataset, vector_header=get_values_and_header(dataset)

#dataset= np.array([[1,2,3,1,3],[1,2,3,2,4],[1,2,7,1,5],[1,2,7,2,6],[1,2,1,1,7],[1,2,1,2,17],[1,2,1,2,17],[1,44,1,1,7],[1,44,1,2,17]])
#x_test=np.array([[1,2,3],[1,2,1]])
features_amount=8
outputs_amount=12

features=dataset[0,0:features_amount]

features=separador_de_features(features_amount,dataset,features)

x_train, x_test = train_test_split(    
    features, test_size=0.15, random_state=1)

#np.savetxt("training_set_re_im_caso_simple_random_state_1.csv",x_train,delimiter=",")
#np.savetxt("testing_set_re_im_caso_simple_random_state_1.csv",x_test,delimiter=",")

vector_header=np.reshape(vector_header,(1,len(vector_header)))


data_test_full, dataset=train_test_full(features_amount,dataset,x_test,outputs_amount)


data_test_full=np.append(vector_header,data_test_full,axis=0)
dataset=np.append(vector_header,dataset,axis=0)

np.savetxt("testing_set_re_im_array_seed_1.csv",data_test_full,delimiter=",",fmt='%s')
np.savetxt("training_set_re_im_array_seed_1_full.csv",dataset,delimiter=",",fmt='%s')
#'''


[[1.00e+00 2.00e-02 4.34e+00 1.30e+01 7.15e+00 7.55e+00 2.80e+01 3.40e+01]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
100.0%


In [61]:
data_test_full.shape

(201, 21)

In [64]:


dataset = pandas.read_csv("C:/path/training_set_re_im_array_seed_1_full.csv", header=None)
dataset, vector_header=get_values_and_header(dataset)

#dataset= np.array([[1,2,3,1,3],[1,2,3,2,4],[1,2,7,1,5],[1,2,7,2,6],[1,2,1,1,7],[1,2,1,2,17],[1,2,1,2,17],[1,44,1,1,7],[1,44,1,2,17]])
#x_test=np.array([[1,2,3],[1,2,1]])
features_amount=8
outputs_amount=12

features=dataset[0,0:features_amount]

features=separador_de_features(features_amount,dataset,features)

x_train, x_test = train_test_split(    
    features, test_size=3/17, random_state=1)

#np.savetxt("training_set_re_im_caso_simple_random_state_1.csv",x_train,delimiter=",")
#np.savetxt("testing_set_re_im_caso_simple_random_state_1.csv",x_test,delimiter=",")

vector_header=np.reshape(vector_header,(1,len(vector_header)))

data_test_full, dataset=train_test_full(features_amount,dataset,x_test,outputs_amount)

data_test_full=np.append(vector_header,data_test_full,axis=0)
dataset=np.append(vector_header,dataset,axis=0)

np.savetxt("validation_set_re_im_array_seed_1_full.csv",data_test_full,delimiter=",",fmt='%s')
np.savetxt("training_set_re_im_array_seed_1_full.csv",dataset,delimiter=",",fmt='%s')
#'''


[[1.00e+00 2.00e-02 4.34e+00 1.30e+01 7.15e+00 7.55e+00 2.80e+01 3.40e+01]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]
100.0%


In [65]:
# Splitting the dataset into 80% training and 20% testing
#x_train, x_test, y_train, y_test = train_test_split(x_train, y_train, test_size=0.2, random_state=42)

#print(x_train.shape)
#print(x_test.shape)

## Load splitted dataset
Load data $x_w$

In [66]:
dataframe = pandas.read_csv(r"C:/path/training_set_re_im_array_seed_1_array_conmls.csv", header=None)
dataframe=dataframe.values
dataframe=np.asfarray(dataframe[1:,0:],float)
    
    #dataframe=np.delete(dataframe,7,1)
x_train = dataframe[:,0:8]
y_train = dataframe[:,8:]
print(x_train.shape)
print(y_train.shape)

c:\users\allan\appdata\local\programs\python\python36\lib\site-packages\IPython\core\interactiveshell.py:3072: DtypeWarning: Columns (0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19) have mixed types.Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


(700000, 8)
(700000, 12)


In [67]:
dataframe = pandas.read_csv(r"C:/path/testing_set_re_im_array_seed_1_array_conmls.csv", header=None)
dataframe=dataframe.values
dataframe=np.asfarray(dataframe[1:,0:],float)
    
    #dataframe=np.delete(dataframe,7,1)
x_test = dataframe[:,0:8]
y_test = dataframe[:,8:]

In [68]:
dataframe = pandas.read_csv(r"C:/path/validation_set_re_im_array_seed_1_array_conmls.csv", header=None)
dataframe=dataframe.values
dataframe=np.asfarray(dataframe[1:,0:],float)
    
    #dataframe=np.delete(dataframe,7,1)
x_val = dataframe[:,0:8]
y_val = dataframe[:,8:]

## Training dataset
Load data

In [69]:
# Create the model
model = Sequential()
model.add(Dense(50, activation='relu', input_dim=x_train.shape[1]))
model.add(Dense(50, activation='relu'))
model.add(Dense(y_train.shape[1]))


$x=\frac{x-\mu}{\sigma}$

In [70]:
    #standarization

standar_1=StandardScaler().fit(x_train)
x_train=standar_1.transform(x_train)
x_val=standar_1.transform(x_val)

x_test=standar_1.transform(x_test)


dump(standar_1, 'standar_input.bin', compress=True)

['standar_input.bin']

In [71]:
# Compile the model
model.compile(optimizer='adam', loss='mse', metrics=['accuracy'])

# Train the model
model.fit(x_train, y_train, epochs=3, verbose=2, validation_data=(x_val, y_val))

# Evaluate the model
loss, accuracy = model.evaluate(x_test, y_test, verbose=0)
print(f'Test loss: {loss:.4f}')
print(f'Test accuracy: {accuracy:.4f}')

model.save("model_.h5")

Train on 700000 samples, validate on 150000 samples
Epoch 1/3
 - 41s - loss: 0.0018 - accuracy: 0.9259 - val_loss: 4.5908e-04 - val_accuracy: 0.9568
Epoch 2/3
 - 42s - loss: 4.1076e-04 - accuracy: 0.9590 - val_loss: 3.6996e-04 - val_accuracy: 0.9621
Epoch 3/3
 - 40s - loss: 3.5162e-04 - accuracy: 0.9624 - val_loss: 3.7395e-04 - val_accuracy: 0.9613
Test loss: 0.0005
Test accuracy: 0.9579


In [72]:


model = load_model('model_.h5')
standar_1=load('standar_input.bin')

model.summary()

Model: "sequential_8"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_17 (Dense)             (None, 50)                450       
_________________________________________________________________
dense_18 (Dense)             (None, 50)                2550      
_________________________________________________________________
dense_19 (Dense)             (None, 12)                612       
Total params: 3,612
Trainable params: 3,612
Non-trainable params: 0
_________________________________________________________________


In [ ]:
#plate_thickness,loss_tan,epsilon_r,antipad_radius,cavity_tickness,pad_radius,pitch,freq

In [ ]:
dataframe = pandas.read_csv(r"C:/path/testing_set_re_im_array_seed_1_array_conmls.csv", header=None)
dataframe=dataframe.values
dataframe=np.asfarray(dataframe[1:,0:],float)
    

x_example = dataframe[0,0:8]
y_expected = dataframe[0,8:]
x_example = x_example.reshape(1, -1)
y_expected = y_expected.reshape(1, -1)

print("Entrada de ejemplo: ")
print(x_example)
print(x_example.shape)

x_example=standar_1.transform(x_example)

print("Salida esperada de ejemplo ejemplo: ")
print(y_expected)
print(y_expected.shape)

In [ ]:
# reS(11),reS(21),reS(13 1),reS(13 2),reS(23 1),reS(23 2),imS(11),imS(21),imS(13 1),imS(13 2),imS(23 1),imS(23 2)
y_predicted = model.predict(x_example)
print("Salida predicha con el ejemplo: ")
print(y_predicted)
print(y_predicted.shape)

In [ ]:
x_example = dataframe[0:200,0:8]
y_expected = dataframe[0:200,8:]
#x_example = x_example.reshape(1, -1)
#y_expected = y_expected.reshape(1, -1)

print("Entrada de ejemplo: ")
print(x_example)
print(x_example.shape)

x_example=standar_1.transform(x_example)

print("Salida esperada de ejemplo ejemplo: ")
print(y_expected)
print(y_expected.shape)

In [ ]:
# reS(11),reS(21),reS(13 1),reS(13 2),reS(23 1),reS(23 2),imS(11),imS(21),imS(13 1),imS(13 2),imS(23 1),imS(23 2)
y_predicted = model.predict(x_example)
print("Salida predicha con el ejemplo: ")
print(y_predicted)
print(y_predicted.shape)

In [ ]:
y_predicted_plot=y_predicted[:,0]
print(y_predicted_plot.shape)

y_expected_plot=y_expected[:,0]
print(y_expected_plot.shape)


x_plot = dataframe[0:200,7]

In [ ]:
# Crear la figura y los ejes
plt.figure(figsize=(10, 6))

# Plotear el primer array
plt.plot(x_plot, y_expected_plot,  label='Esperado', color='blue')
# Plotear el segundo array sobre el mismo gráfico
plt.plot(x_plot, y_predicted_plot, label='Predicho', color='red')

# Añadir leyenda y etiquetas
plt.legend()
plt.title("Comparación")
plt.xlabel("Frecuencia (GHz)")
plt.ylabel("Parte real reflexion")

# Mostrar el gráfico
plt.show()